# Multiple Linear Regression

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv('/content/kc_house_data.csv')
dataset.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   
1      7242     2.0           0     0  ...      7        2170            400   
2     10000     1.0           0     0  ...      6         770              0   
3      5000     1.0           0     0  ...      7        1050            910   
4      8080     1.0           0     0  ...      8        1680              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  

[5 rows x 21 columns]

In [3]:
dataset.columns

Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15'],
      dtype='object')

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   id             21613 non-null  int64  
 1   date           21613 non-null  object 
 2   price          21613 non-null  float64
 3   bedrooms       21613 non-null  int64  
 4   bathrooms      21613 non-null  float64
 5   sqft_living    21613 non-null  int64  
 6   sqft_lot       21613 non-null  int64  
 7   floors         21613 non-null  float64
 8   waterfront     21613 non-null  int64  
 9   view           21613 non-null  int64  
 10  condition      21613 non-null  int64  
 11  grade          21613 non-null  int64  
 12  sqft_above     21613 non-null  int64  
 13  sqft_basement  21613 non-null  int64  
 14  yr_built       21613 non-null  int64  
 15  yr_renovated   21613 non-null  int64  
 16  zipcode        21613 non-null  int64  
 17  lat            21613 non-null  float64
 18  long  

In [5]:
dataset.drop('date', axis=1, inplace=True)
dataset.head()

id     price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  \
0  7129300520  221900.0         3       1.00         1180      5650     1.0   
1  6414100192  538000.0         3       2.25         2570      7242     2.0   
2  5631500400  180000.0         2       1.00          770     10000     1.0   
3  2487200875  604000.0         4       3.00         1960      5000     1.0   
4  1954400510  510000.0         3       2.00         1680      8080     1.0   

   waterfront  view  condition  grade  sqft_above  sqft_basement  yr_built  \
0           0     0          3      7        1180              0      1955   
1           0     0          3      7        2170            400      1951   
2           0     0          3      6         770              0      1933   
3           0     0          5      7        1050            910      1965   
4           0     0          3      8        1680              0      1987   

   yr_renovated  zipcode      lat     long  sqft_living15  sqft_lot15  
0             0    98178  47.5112 -122.257           1340        5650  
1          1991    98125  47.7210 -122.319           1690        7639  
2             0    98028  47.7379 -122.233           2720        8062  
3             0    98136  47.5208 -122.393           1360        5000  
4             0    98074  47.6168 -122.045           1800        7503

In [6]:
dataset.shape

(21613, 20)

In [7]:
dataset[0:5]

id     price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  \
0  7129300520  221900.0         3       1.00         1180      5650     1.0   
1  6414100192  538000.0         3       2.25         2570      7242     2.0   
2  5631500400  180000.0         2       1.00          770     10000     1.0   
3  2487200875  604000.0         4       3.00         1960      5000     1.0   
4  1954400510  510000.0         3       2.00         1680      8080     1.0   

   waterfront  view  condition  grade  sqft_above  sqft_basement  yr_built  \
0           0     0          3      7        1180              0      1955   
1           0     0          3      7        2170            400      1951   
2           0     0          3      6         770              0      1933   
3           0     0          5      7        1050            910      1965   
4           0     0          3      8        1680              0      1987   

   yr_renovated  zipcode      lat     long  sqft_living15  sqft_lot15  
0             0    98178  47.5112 -122.257           1340        5650  
1          1991    98125  47.7210 -122.319           1690        7639  
2             0    98028  47.7379 -122.233           2720        8062  
3             0    98136  47.5208 -122.393           1360        5000  
4             0    98074  47.6168 -122.045           1800        7503

In [8]:
dataset[0:5].values

array([[ 7.12930052e+09,  2.21900000e+05,  3.00000000e+00,
         1.00000000e+00,  1.18000000e+03,  5.65000000e+03,
         1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         3.00000000e+00,  7.00000000e+00,  1.18000000e+03,
         0.00000000e+00,  1.95500000e+03,  0.00000000e+00,
         9.81780000e+04,  4.75112000e+01, -1.22257000e+02,
         1.34000000e+03,  5.65000000e+03],
       [ 6.41410019e+09,  5.38000000e+05,  3.00000000e+00,
         2.25000000e+00,  2.57000000e+03,  7.24200000e+03,
         2.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         3.00000000e+00,  7.00000000e+00,  2.17000000e+03,
         4.00000000e+02,  1.95100000e+03,  1.99100000e+03,
         9.81250000e+04,  4.77210000e+01, -1.22319000e+02,
         1.69000000e+03,  7.63900000e+03],
       [ 5.63150040e+09,  1.80000000e+05,  2.00000000e+00,
         1.00000000e+00,  7.70000000e+02,  1.00000000e+04,
         1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         3.00000000e+00,  6.0

In [18]:
X = dataset.drop('price', axis=1).values
y = dataset.iloc[:, 1].values  # price

In [19]:
X

array([[ 7.1e+09,  3.0e+00,  1.0e+00, ..., -1.2e+02,  1.3e+03,  5.6e+03],
       [ 6.4e+09,  3.0e+00,  2.2e+00, ..., -1.2e+02,  1.7e+03,  7.6e+03],
       [ 5.6e+09,  2.0e+00,  1.0e+00, ..., -1.2e+02,  2.7e+03,  8.1e+03],
       ...,
       [ 1.5e+09,  2.0e+00,  7.5e-01, ..., -1.2e+02,  1.0e+03,  2.0e+03],
       [ 2.9e+08,  3.0e+00,  2.5e+00, ..., -1.2e+02,  1.4e+03,  1.3e+03],
       [ 1.5e+09,  2.0e+00,  7.5e-01, ..., -1.2e+02,  1.0e+03,  1.4e+03]])

In [21]:
y

array([221900., 538000., 180000., ..., 402101., 400000., 325000.])

In [12]:
!pip install scikit-learn

## Splitting the dataset into the Training set and Test set

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 12)

In [23]:
y_train

array([279000., 330000., 754950., ..., 780000., 455000., 538250.])

In [25]:
X_test

array([[ 1.8e+09,  5.0e+00,  1.5e+00, ..., -1.2e+02,  1.7e+03,  9.5e+03],
       [ 6.4e+09,  3.0e+00,  1.5e+00, ..., -1.2e+02,  1.6e+03,  1.6e+04],
       [ 8.1e+09,  3.0e+00,  1.8e+00, ..., -1.2e+02,  1.8e+03,  9.7e+03],
       ...,
       [ 8.2e+09,  3.0e+00,  1.8e+00, ..., -1.2e+02,  1.7e+03,  9.5e+03],
       [ 9.5e+09,  2.0e+00,  1.0e+00, ..., -1.2e+02,  1.5e+03,  3.5e+03],
       [ 3.6e+09,  4.0e+00,  2.5e+00, ..., -1.2e+02,  3.0e+03,  5.6e+03]])

In [15]:
y_test

2019     275000.0
3435     279000.0
15940    200500.0
9811     750000.0
18665    395000.0
           ...   
3390     579000.0
6801     599000.0
4775     248500.0
10634    645000.0
1529     810000.0
Name: price, Length: 4323, dtype: float64

## Training the Multiple Linear Regression model on the Training set

In [24]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression() # model name
regressor.fit(X_train, y_train)

LinearRegression()

## Predicting the Test set results

In [27]:
y_pred = regressor.predict(X_test)   # y_test should not be passed as it is the ground truth
np.set_printoptions(precision=1)   # 1 decimal place only
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))  # converting 1D to 2D array

[[285386.6 275000. ]
 [101248.5 279000. ]
 [255554.6 200500. ]
 ...
 [417924.5 248500. ]
 [489889.9 645000. ]
 [766620.7 810000. ]]


## Evaluating the Model Performance

In [28]:
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
r2_score(y_test, y_pred)

0.6856379732491951

In [29]:
np.sqrt(mean_squared_error(y_test,y_pred))  # rmse- root mean square error

np.float64(219778.59867080106)

In [30]:
mean_absolute_error(y_test, y_pred)   # np.abs(y_test - y_pred)

127794.29621435811